services:
  db-ods:
    image: edfialliance/ods-api-db-ods-sandbox:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
    volumes:
      - vol-db-ods:/var/lib/postgresql/data
    ports:
      - "5403:5432"
    restart: always
    container_name: ed-fi-db-ods
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      start_period: "60s"
      retries: 3

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    depends_on:
      - dashboard
    restart: always
    container_name: ed-fi-caddy

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-ods:5432/EdFi_Ods_Sandbox_populated"
    ports:
      - "3000:3000"
    depends_on:
      db-ods:
        condition: service_healthy
    restart: always
    container_name: ed-fi-dashboard

volumes:
  vol-db-ods:
    driver: local
    name: vol-db-ods
  caddy-data:
    driver: local
