services:
  db-ods:
    image: edfialliance/ods-api-db-ods-sandbox:${TAG:-7.3.0}
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
    volumes:
      - vol-db-ods:/var/lib/postgresql/data
    ports:
      - "5403:5432"
    restart: always
    container_name: ed-fi-db-ods
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      start_period: "60s"
      retries: 3

volumes:
  vol-db-ods:
    driver: local
    name: vol-db-ods
